parameters:
  cors_allow_origin: '%env(CORS_ALLOW_ORIGIN)%'
  default_admin_password: 'ChangeMe123'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'

  App\EventSubscriber\CorsSubscriber:
    arguments:
      $allowedOrigin: '%cors_allow_origin%'

  App\Command\SeedAdminUserCommand:
    arguments:
      $adminPassword: '%env(default:default_admin_password:MAXIME_ADMIN_PASSWORD)%'
